CREATE TABLE CITIES(
    CITY CHAR(20) NOT NULL,
    STATE CHAR(20) NOT NULL,
    PRIMARY KEY (CITY)
);

CREATE TABLE WAREHOUSES(
    WID INTEGER NOT NULL,
    WNAME CHAR(30) NOT NULL,
    LOCATION CHAR(20) NOT NULL,
    CITY CHAR(20) NOT NULL,
    EXTRA_CONTEXT JSON,
    PRIMARY KEY (WID),
    FOREIGN KEY (CITY) REFERENCES CITIES(CITY)
);

CREATE TABLE STORES(
    SID INTEGER NOT NULL,
    STORE_NAME CHAR(20) NOT NULL,
    LOCATION_CITY CHAR(20) NOT NULL,
    WID INTEGER NOT NULL,
    PRIMARY KEY (SID),
    FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

CREATE TABLE CUSTOMER(
    CNO INTEGER NOT NULL,
    CNAME CHAR(50) NOT NULL,
    ADDR VARCHAR(50),
    CU_CITY CHAR(20) NOT NULL,
    PRIMARY KEY (CNO)
);

CREATE TABLE ORDERS(
    ONO INTEGER NOT NULL,
    ODATE DATE NOT NULL,
    CNO INTEGER NOT NULL,
    PRIMARY KEY (ONO),
    FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

CREATE TABLE ITEMS(
    ITEMNO INTEGER NOT NULL,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2),
    PRIMARY KEY (ITEMNO)
);

CREATE TABLE ORDERS_ITEMS(
    ONO INTEGER NOT NULL,
    ITEMNO INTEGER NOT NULL,
    ORDERED_QUANTITY INTEGER,
    PRIMARY KEY (ONO, ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS(ONO),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);

CREATE TABLE STORES_ITEMS(
    SID INTEGER NOT NULL,
    ITEMNO INTEGER NOT NULL,
    QUANTITY INTEGER,
    PRIMARY KEY (SID, ITEMNO),
    FOREIGN KEY (SID) REFERENCES STORES(SID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS(ITEMNO)
);
